"""Shell completion scripts generated from the argument parser (#173).

No completion library: the parser knows every subcommand and option, and
each shell needs only a few lines to use that. Install with, for example,
`gpp completions bash >> ~/.bashrc` or `gpp completions fish >
~/.config/fish/completions/gpp.fish`.
"""

from __future__ import annotations

import argparse

SHELLS = ("bash", "zsh", "fish", "powershell")


def _subcommands(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return dict(action.choices)
    return {}


def _options(parser: argparse.ArgumentParser) -> list[str]:
    out: list[str] = []
    for action in parser._actions:
        out.extend(o for o in action.option_strings if o.startswith("--"))
    return sorted(set(out))


def _help(parser: argparse.ArgumentParser, name: str) -> str:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            for choice in action._choices_actions:
                if choice.dest == name:
                    return (choice.help or "").replace("'", "").replace('"', "")
    return ""


def script(parser: argparse.ArgumentParser, shell: str) -> str:
    if shell not in SHELLS:
        raise ValueError(f"shell must be one of {SHELLS}")
    subs = _subcommands(parser)
    names = " ".join(sorted(subs))
    top = " ".join(_options(parser))
    if shell == "bash":
        cases = "\n".join(
            f'        {name}) COMPREPLY=($(compgen -W "{" ".join(_options(sub))}" -- "$cur")) ;;'
            for name, sub in sorted(subs.items())
        )
        return f"""# gpp bash completion -- generated by `gpp completions bash`
_gpp() {{
    local cur prev sub
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    sub="${{COMP_WORDS[1]}}"
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=($(compgen -W "{names} {top}" -- "$cur"))
        return
    fi
    case "$sub" in
{cases}
        *) COMPREPLY=($(compgen -f -- "$cur")) ;;
    esac
}}
complete -F _gpp gpp
"""
    if shell == "zsh":
        lines = "\n".join(f"    '{name}:{_help(parser, name)}'" for name in sorted(subs))
        cases = "\n".join(
            f"        {name}) _arguments {' '.join(repr(o) for o in _options(sub))} '*:file:_files' ;;"
            for name, sub in sorted(subs.items())
        )
        return f"""#compdef gpp
# gpp zsh completion -- generated by `gpp completions zsh`
_gpp() {{
    local -a subcommands
    subcommands=(
{lines}
    )
    if (( CURRENT == 2 )); then
        _describe 'command' subcommands
        return
    fi
    case "${{words[2]}}" in
{cases}
    esac
}}
_gpp "$@"
"""
    if shell == "fish":
        lines = ["# gpp fish completion -- generated by `gpp completions fish`"]
        for name in sorted(subs):
            lines.append(
                f"complete -c gpp -n '__fish_use_subcommand' -a {name} -d '{_help(parser, name)}'"
            )
        for name, sub in sorted(subs.items()):
            for option in _options(sub):
                lines.append(
                    f"complete -c gpp -n '__fish_seen_subcommand_from {name}' -l {option[2:]}"
                )
        return "\n".join(lines) + "\n"
    # powershell
    table = ", ".join(
        f"'{name}' = @({', '.join(repr(o) for o in _options(sub))})"
        for name, sub in sorted(subs.items())
    )
    return f"""# gpp PowerShell completion -- generated by `gpp completions powershell`
Register-ArgumentCompleter -Native -CommandName gpp -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)
    $subs = @('{"', '".join(sorted(subs))}')
    $options = @{{ {table} }}
    $words = $commandAst.CommandElements | ForEach-Object {{ $_.ToString() }}
    if ($words.Count -le 2 -and -not ($subs -contains $words[1])) {{
        $subs | Where-Object {{ $_ -like "$wordToComplete*" }} | ForEach-Object {{
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }}
        return
    }}
    $sub = $words[1]
    if ($options.ContainsKey($sub)) {{
        $options[$sub] | Where-Object {{ $_ -like "$wordToComplete*" }} | ForEach-Object {{
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)
        }}
    }}
}}
"""
